//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int product_id { get; set; }
        public int category_id { get; set; }
        public string product_name { get; set; }
        public decimal product_price { get; set; }
        public byte[] product_img { get; set; }
        public Nullable<int> product_quantity { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
