//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IDUser { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string PhoneNumer { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
